version: '3.4'

networks:
  frontend:
  backend:
  

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: .\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: ad
      DatabasePassword: offByBit
      ExternalCatalogBaseUrl: http://localhost:51303

